/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.neu.carApp;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author 18573
 */
public class CreateCar extends javax.swing.JPanel {

    /**
     * Creates new form CreateCar
     */
    
    CarProperties carProperties;
    CarPropertyObjects carPropertyObjects;
    
    public CreateCar() {
        initComponents();
    }

    CreateCar(CarProperties carProperties, CarPropertyObjects carPropertyObjects) {

        initComponents();
        this.carProperties = carProperties;
        this.carPropertyObjects = carPropertyObjects;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblCarName = new javax.swing.JLabel();
        lblPassengerCar = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblYearOfManufacture = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblMaintenanceCertValidity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        rbPasssengerCarYes = new javax.swing.JRadioButton();
        rbPassengerCarNo = new javax.swing.JRadioButton();
        rbAvailabilityYes = new javax.swing.JRadioButton();
        rbAvailabilityNo = new javax.swing.JRadioButton();
        txtManufacturer = new javax.swing.JTextField();
        txtYeatOfManufacture = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        rbMCVYes = new javax.swing.JRadioButton();
        rbMCVNo = new javax.swing.JRadioButton();
        cbCity = new javax.swing.JComboBox<>();
        lblUploadFIle = new javax.swing.JLabel();
        btnUploadFIle = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        lblCarName.setText("Car Name ");

        lblPassengerCar.setText("Passenger Car");

        lblAvailability.setText("Availability");

        lblManufacturer.setText("Manufacturer");

        lblYearOfManufacture.setText("Year of Manufacture");

        lblSeats.setText("Seats");

        lblSerialNumber.setText("Serial Number");

        lblModelNumber.setText("Model Number");

        lblMaintenanceCertValidity.setText("Maintenance Certificate Validity");

        lblCity.setText("City");

        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPasssengerCarYes);
        rbPasssengerCarYes.setText("Yes");

        buttonGroup1.add(rbPassengerCarNo);
        rbPassengerCarNo.setText("No");
        rbPassengerCarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPassengerCarNoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbAvailabilityYes);
        rbAvailabilityYes.setText("Yes");

        buttonGroup2.add(rbAvailabilityNo);
        rbAvailabilityNo.setText("No");

        txtYeatOfManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYeatOfManufactureActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbMCVYes);
        rbMCVYes.setSelected(true);
        rbMCVYes.setText("Yes");

        buttonGroup3.add(rbMCVNo);
        rbMCVNo.setText("No");

        cbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Jersey City", "Hoboken", "New York City" }));
        cbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCityActionPerformed(evt);
            }
        });

        lblUploadFIle.setText("Upload File");

        btnUploadFIle.setText("Select File");

        btnCreate.setText("Create/Update");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblYearOfManufacture, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(lblManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassengerCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPasssengerCarYes)
                        .addGap(18, 18, 18)
                        .addComponent(rbPassengerCarNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbAvailabilityYes)
                        .addGap(18, 18, 18)
                        .addComponent(rbAvailabilityNo))
                    .addComponent(txtManufacturer)
                    .addComponent(txtYeatOfManufacture, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(txtSeats)
                    .addComponent(txtSerialNumber)
                    .addComponent(txtModelNumber))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaintenanceCertValidity)
                                .addGap(18, 18, 18)
                                .addComponent(rbMCVYes)
                                .addGap(18, 18, 18)
                                .addComponent(rbMCVNo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblUploadFIle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUploadFIle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnCreate)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassengerCar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPasssengerCarYes)
                        .addComponent(rbPassengerCarNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAvailability)
                        .addComponent(rbAvailabilityYes)
                        .addComponent(rbAvailabilityNo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaintenanceCertValidity)
                        .addComponent(rbMCVYes)
                        .addComponent(rbMCVNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCity)
                        .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYearOfManufacture)
                    .addComponent(txtYeatOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeats)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUploadFIle)
                        .addComponent(btnUploadFIle)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelNumber)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCreate)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void rbPassengerCarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPassengerCarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPassengerCarNoActionPerformed

    private void txtYeatOfManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYeatOfManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYeatOfManufactureActionPerformed

    private void cbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCityActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        System.out.println(carPropertyObjects.getCarMap());
        CarProperties carProperties = new CarProperties();
        carProperties.setCarName(txtCarName.getText());
        
        if(rbPasssengerCarYes.isSelected())
            carProperties.setPassengerCar(true);
        else if(rbPassengerCarNo.isSelected())
            carProperties.setPassengerCar(false);
        
        if(rbAvailabilityYes.isSelected())
            carProperties.setAvailability(true);
        else if(rbAvailabilityNo.isSelected())
            carProperties.setAvailability(false);
             
        carProperties.setManufacturer(txtManufacturer.getText());
        carProperties.setYearOfManufacture(Integer.parseInt(txtYeatOfManufacture.getText()));
        carProperties.setSeats(Integer.parseInt(txtSeats.getText()));
        carProperties.setSerialNumber(Integer.parseInt(txtSerialNumber.getText()));
        carProperties.setModelNumber(Integer.parseInt(txtModelNumber.getText()));
        
        if(rbMCVYes.isSelected())
            carProperties.setValidity(true);
        else if(rbMCVNo.isSelected())
            carProperties.setValidity(false);
        
        carProperties.setCity(cbCity.getSelectedItem().toString());
        HashMap<Integer, CarProperties> tempMap = new HashMap<Integer, CarProperties>();
        tempMap = carPropertyObjects.getCarMap();
        tempMap.put(carProperties.getSerialNumber(), carProperties);
        carPropertyObjects.setCarMap(tempMap);
        System.out.println(carPropertyObjects.getCarMap());
        System.out.println(carPropertyObjects.getCarMap().get(1).getModelNumber());
        if(carPropertyObjects.getCarMap().get(2) != null) {
           System.out.println(carPropertyObjects.getCarMap().get(2).getModelNumber()); 
        }
        
        JOptionPane.showMessageDialog(this, "Record Created");
        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUploadFIle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintenanceCertValidity;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblPassengerCar;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblUploadFIle;
    private javax.swing.JLabel lblYearOfManufacture;
    private javax.swing.JRadioButton rbAvailabilityNo;
    private javax.swing.JRadioButton rbAvailabilityYes;
    private javax.swing.JRadioButton rbMCVNo;
    private javax.swing.JRadioButton rbMCVYes;
    private javax.swing.JRadioButton rbPassengerCarNo;
    private javax.swing.JRadioButton rbPasssengerCarYes;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYeatOfManufacture;
    // End of variables declaration//GEN-END:variables
}
